### ISSUE TITLE
Create a reusable action for installation of vcpkg

### ISSUE THREAD

**Issue by bldrvnlw** [ManiVaultStudio/github-actions#6]
In ManiVaultStudio/ExamplePlugins there is some boilerplate vcpkg code is being added to the build.yml. This can be moved to this repo (ManiVault/github-actions) as a reusable, centrally maintained, action with parameters for the repo specific stuff.

**Comment by alxvth** [comment]
Initially I followed [this guide](https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-packages) to setup binary caching for vcpkg artifacts with NuGet. I now think that using `actions/cache` is a more straight-forward way, see https://github.com/ManiVaultStudio/ExamplePlugins/pull/53. 
The main (potential) benefit with NuGet is that artifacts are published and could be re-used across repositories, but I don't think we need this atm. The NuGet comes with more maintenance, e.g. managing GitHub secrets.

We could use this basic setup as a custom, re-usable action:
```yaml
env:
  VCPKG_COMMIT_SHA: 56bb2411609227288b70117ead2c47585ba07713 # corresponds to tag 2026.04.27
```
The `VCPKG_COMMIT_SHA` should be a user-definable input with a default that we can update centrally.
The main chunk it:
```yaml
      - name: Set vcpkg environment (Unix)
        if: "!startsWith(runner.os, 'Windows')"
        run: |
          echo "VCPKG_DIR=${{ runner.temp }}/vcpkg" >> $GITHUB_ENV
          echo "VCPKG_ROOT=${{ runner.temp }}/vcpkg" >> $GITHUB_ENV
          echo "VCPKG_BINARY_SOURCES=clear;files,${{ runner.temp }}/vcpkg-cache,readwrite" >> $GITHUB_ENV

      - name: Set vcpkg environmentg (Windows)
        if: startsWith(runner.os, 'Windows')
        shell: pwsh
        run: |
          echo "VCPKG_DIR=${{ runner.temp }}/vcpkg" >> $env:GITHUB_ENV
          echo "VCPKG_ROOT=${{ runner.temp }}/vcpkg" >> $env:GITHUB_ENV
          echo "VCPKG_BINARY_SOURCES=clear;files,${{ runner.temp }}/vcpkg-cache,readwrite" >> $env:GITHUB_ENV

      - name: Set up binary cache
        uses: actions/cache@v5
        with:
          path: ${{ runner.temp }}/vcpkg-cache
          key: vcpkg-cache-${{ runner.os }}-${{ matrix.os }}-${{ matrix.build-cversion }}-${{ env.VCPKG_COMMIT_SHA }}-${{ hashFiles('**/vcpkg.json', '**/vcpkg-overlays/**') }}
          restore-keys: |
            vcpkg-cache-${{ runner.os }}-${{ matrix.os }}-${{ matrix.build-cversion }}-${{ env.VCPKG_COMMIT_SHA }}

      - name: Clone and checkout vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git --branch master ${{ env.VCPKG_DIR }}
          git -C ${{ env.VCPKG_DIR }} checkout ${{ env.VCPKG_COMMIT_SHA }}

      - name: Bootstrap vcpkg (Unix)
        if: "!startsWith(runner.os, 'Windows')"
        run: ${{ env.VCPKG_DIR }}/bootstrap-vcpkg.sh -disableMetrics

      - name: Bootstrap vcpkg (Windows)
        if: startsWith(runner.os, 'Windows')
        shell: pwsh
        run: ${{ env.VCPKG_DIR }}/bootstrap-vcpkg.bat -disableMetrics
```

**Comment by bldrvnlw** [comment]
I'm working on this in the new ManiVaultStudio/vcpkg-registry - you can have a peek thete in the test_build.yaml workflow . I think the way Im doing it there will be transferrable - its using actions/cache

**Comment by alxvth** [comment]
One possible setup that is currently used in the [ExamplePlugin](https://github.com/ManiVaultStudio/ExamplePlugins/blob/master/.github/workflows/build.yml) repo using actions/cache instead of NuGet:
```yaml
      - name: Set up binary cache
        uses: actions/cache@v6
        with:
          path: ${{ runner.temp }}/vcpkg-cache
          key: vcpkg-cache-${{ runner.os }}-${{ matrix.os }}-${{ matrix.build-cversion }}-${{ env.VCPKG_COMMIT_SHA }}-${{ hashFiles('**/vcpkg.json', '**/vcpkg-overlays/**') }}
          restore-keys: |
            vcpkg-cache-${{ runner.os }}-${{ matrix.os }}-${{ matrix.build-cversion }}-${{ env.VCPKG_COMMIT_SHA }}

      - name: Clone and checkout vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git --branch master ${{ env.VCPKG_DIR }}
          git -C ${{ env.VCPKG_DIR }} checkout ${{ env.VCPKG_COMMIT_SHA }}

      - name: Bootstrap vcpkg (Unix)
        if: "!startsWith(runner.os, 'Windows')"
        run: ${{ env.VCPKG_DIR }}/bootstrap-vcpkg.sh -disableMetrics

      - name: Bootstrap vcpkg (Windows)
        if: startsWith(runner.os, 'Windows')
        shell: pwsh
        run: ${{ env.VCPKG_DIR }}/bootstrap-vcpkg.bat -disableMetrics
```
The `VCPKG_COMMIT_SHA` has to be defined as before.
